### ISSUE TITLE
no orders hasMany relation for User model

### ISSUE THREAD

**Issue by vdomah** [lovata/oc-orders-shopaholic-plugin#14]
Hi!
Seems like User model doesn't have orders relation after installing Orders plugin. I've found declaration of reverse relation: user in Order model. So I think will be great to to declare orders also. Correct me if I'm not seeing something
Thanks!

**Comment by kharanenka** [comment]
Hi! You are right, now there is no such relation. We plan to add the plugin "My orders for Shopaholic" to the marketplace. In this plugin, relation between the User and Order models will be added + the ability to display the order history of the user will be added.

**Comment by vdomah** [comment]
Your choice :)

**Comment by kharanenka** [comment]
Fixed in version 1.6.0
