### ISSUE TITLE
Can't display order.secret_key

### ISSUE THREAD

**Issue by philmarc** [lovata/oc-orders-shopaholic-plugin#25]
I am using the latest update of the plugin, and I have checked that I have a column `secret_key` in the database (`lovata_orders_shopaholic_orders` table) that is not empty.

When I access my url `example.com/account/order/265416079c0e42f4f1c131388cf366d1`, my order info is displayed correctly, except for the `secret_key` 

```
    {% set order = OrderPage.get() %}
    <p>{{ order.order_number }}</p> <!-- works fine -->
    <p>{{ order.secret_key }}</p> <!-- doesn't work -->
```

The reason I need the `secret_key` is to display a list of orders in the account dashboard:
```
{% set orders = obUser.order() %}
{% for order in orders %}
<a href="{{ 'account'|page({param1: 'order', param2: order.secret_key}) }}" data-push-state>#{{ order.order_number }}</a>
{% endfor %}
```

Why can't I display the `order.secret_key` , or what am I missing?

**Comment by kharanenka** [comment]
Fixed in version 1.9.1
