### ISSUE TITLE
[Question] Rainlab user

### ISSUE THREAD

**Issue by pvullioud** [lovata/oc-orders-shopaholic-plugin#3]
Hi,
Why did you choose to develop an other user manager (Buddies)?
If a site is already using [rainlab-user](http://octobercms.com/plugin/rainlab-user), how can I integrate your shop with it?
Thanks

**Comment by lautsevich** [comment]
Hi Pierre-André,

Thank you for your interest in our plugins!

User and Buddies plugins share similar functionality. But Buddies provides the following benefits:

1. All error notifications are outputted into lang files. This allows full, convenient manipulation and localization.
2. Integrated features that allow to expand the user properties without the necessity of installing additional plugins, such as [User Plus+](http://octobercms.com/plugin/rainlab-userplus) and [User Plus](http://octobercms.com/plugin/indikator-user). To do this you have to fill out the corresponding fields in the admin area.
3. Buddies’ source code, same as every other of our plugins, is fully covered by unit tests. This allows you to have full control of reliability automatically, by incorporating testing in to your CI process. Very soon we are planning to introduce Codeception acceptance testing into our plugins, which could also be used in the same way.
4. We are building a large ecosystem of plugins for OcotberCMS. The first 9 of them are already released in October Marketplace, while 5 more are at the stage of active development, getting ready to be released in the coming months. This is why the plugins that play an important role in the ecosystem’s functionality are being developed according to general requirements for best integration of plugins with each other.
 
As for integration with the User plugin, we are considering the possibility, but the decision has not been made and the deadline for this feature has not been set. However you can integrate the Orders plugin yourself by making small changes to the plugin’s code and block updates.
 
If you plan on actively using Shopaholic we recommend you to use it with the Buddies plugin.

Have a nice experience with Shopaholic! ;)

**Comment by pvullioud** [comment]
Thanks for your reply. I'll test Shopaholic soon.

**Comment by lautsevich** [comment]
No problem! Have a nice experience with Shopaholic! 👍
