### ISSUE TITLE
Bug: order secret_key can contain slash and it crashed route

### ISSUE THREAD

**Issue by riartem** [lovata/oc-orders-shopaholic-plugin#4]
I try to manually test that plugin and on newly created order I have slash in auto generated 'secret_key' field:
![image](https://user-images.githubusercontent.com/987517/34280859-c572b684-e6cb-11e7-9e3b-8d84c20c86e3.png)

And (of cource) It crashes route:
![image](https://user-images.githubusercontent.com/987517/34280881-eb430210-e6cb-11e7-86fc-f03d170a0c90.png)

I think if that secret will contain only alphanumeric symbols it would be enough.

**Comment by kharanenka** [comment]
Fixed in version 1.0.3
