### ISSUE TITLE
[Question]: OrderPage with coupons

### ISSUE THREAD

**Issue by vosco88** [lovata/oc-orders-shopaholic-plugin#43]
Hi, with OrderPage component, is there a way to get all applied coupons with their respective information so I can show it to user in a summary of order? So far I was able to get coupon_list but that is just an array of coupon codes. 

Thank you

**Comment by kharanenka** [comment]
Hi @vosco88! 
It is possible to get list applied coupon codes from [OrderItem](https://github.com/lovata/oc-shopaholic-plugin/wiki/OrderItem) object (coupon_list field).
If you need to get detailed information about price changes, you can use position_total_price_data, shipping_price_data, total_price_data fields in [OrderItem](https://github.com/lovata/oc-shopaholic-plugin/wiki/OrderItem) order object.
These fields return [PriceContainer](https://github.com/lovata/oc-shopaholic-plugin/wiki/PriceContainer) class object.

Perhaps you will be enough to use information from logs of changing prices.
