### ISSUE TITLE
[Bug] [Orders] Wrong link at update page

### ISSUE THREAD

**Issue by rizhenkov** [lovata/oc-orders-shopaholic-plugin#45]
When we look at the "Order positions" we can update exist position by click on it.
At this page we have a "Cancel" link which goes to /backend/lovata/ordersshopaholic/orderpositions (404 Not found)

![image](https://user-images.githubusercontent.com/987517/48485012-c4081500-e828-11e8-807e-578530fa5ef7.png)

**Comment by kharanenka** [comment]
Fixed in version 1.14.2
