### ISSUE TITLE
Don't show all payment methods

### ISSUE THREAD

**Issue by martinBadin** [lovata/oc-orders-shopaholic-plugin#5]
Hi,

I use your code from plugin shop, but this code don't show all my payment method. Show only first payment method.

Example
`
{% set obPaymentMethodList = PaymentMethodList.make().sort().active() %}
`

but if I remove the method `sort()`, are showing all payment methods.

I created payment methods with names `Dobierka` and `Prevodom na účet` and all payment methods are active.

Thanks for help

**Comment by kharanenka** [comment]
Thank you for your interest in our plugins! Fixed in version 1.0.4
